[2024-10-13T10:33:19.859+0000] {processor.py:186} INFO - Started process (PID=50529) to work on /home/dblab/haeun/mlops/ml_airflow/ex1/venv/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-10-13T10:33:19.860+0000] {processor.py:914} INFO - Processing file /home/dblab/haeun/mlops/ml_airflow/ex1/venv/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2024-10-13T10:33:19.861+0000] {logging_mixin.py:190} INFO - [2024-10-13T10:33:19.861+0000] {dagbag.py:588} INFO - Filling up the DagBag from /home/dblab/haeun/mlops/ml_airflow/ex1/venv/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-10-13T10:33:19.862+0000] {logging_mixin.py:190} INFO - [2024-10-13T10:33:19.861+0000] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/dblab/haeun/mlops/ml_airflow/ex1/venv/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2024-10-13T10:33:19.862+0000] {logging_mixin.py:190} INFO - [2024-10-13T10:33:19.862+0000] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2024-10-13T10:33:19.862+0000] {processor.py:927} WARNING - No viable dags retrieved from /home/dblab/haeun/mlops/ml_airflow/ex1/venv/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-10-13T10:33:19.869+0000] {processor.py:208} INFO - Processing /home/dblab/haeun/mlops/ml_airflow/ex1/venv/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.012 seconds
[2024-10-13T10:33:50.555+0000] {processor.py:186} INFO - Started process (PID=51019) to work on /home/dblab/haeun/mlops/ml_airflow/ex1/venv/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-10-13T10:33:50.555+0000] {processor.py:914} INFO - Processing file /home/dblab/haeun/mlops/ml_airflow/ex1/venv/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2024-10-13T10:33:50.556+0000] {logging_mixin.py:190} INFO - [2024-10-13T10:33:50.556+0000] {dagbag.py:588} INFO - Filling up the DagBag from /home/dblab/haeun/mlops/ml_airflow/ex1/venv/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-10-13T10:33:50.557+0000] {logging_mixin.py:190} INFO - [2024-10-13T10:33:50.557+0000] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/dblab/haeun/mlops/ml_airflow/ex1/venv/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2024-10-13T10:33:50.557+0000] {logging_mixin.py:190} INFO - [2024-10-13T10:33:50.557+0000] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2024-10-13T10:33:50.557+0000] {processor.py:927} WARNING - No viable dags retrieved from /home/dblab/haeun/mlops/ml_airflow/ex1/venv/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-10-13T10:33:50.564+0000] {processor.py:208} INFO - Processing /home/dblab/haeun/mlops/ml_airflow/ex1/venv/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.011 seconds
